#!/usr/bin/env python3
"""Render every host dialect from personas/ + team.yaml + hosts/.

Generated trees are never hand-edited; `check.py --drift` fails if they differ from what
this script would write. Requires PyYAML (a dev-time dependency); scripts that ship to
users, such as the bootstrap script, stay standard-library only.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("gen.py needs PyYAML: pip install pyyaml")

ROOT = pathlib.Path(__file__).resolve().parent.parent
PERSONAS = ROOT / "personas"
SHARED = PERSONAS / "_shared"
HOSTS = ROOT / "hosts"
DIST = ROOT / "dist"

BANNER = "<!-- generated by tools/gen.py from personas/ — do not edit -->"


def load_team():
    return yaml.safe_load((ROOT / "team.yaml").read_text())


def load_personas():
    out = {}
    for f in sorted(PERSONAS.glob("*.yaml")):
        d = yaml.safe_load(f.read_text())
        body = (PERSONAS / d["prompt"]).read_text()
        # the prompt file carries its own tiny frontmatter, currently just r4
        _, fm, rest = body.split("---", 2)
        d["_front"] = yaml.safe_load(fm) or {}
        d["_body"] = rest.strip()
        out[d["name"]] = d
    return out


def shared(name: str) -> str:
    return (SHARED / f"{name}.md").read_text().strip()


CONTRACT = """## The contract

This host does not deliver `AGENTS.md` to you, so the contract is stated here rather than
assumed. Read the project's `AGENTS.md` yourself if you need its project-specific bindings.

- The Tech-Lead is the only voice to the user and the only persona that posts externally.
- Specialists return findings; they never post, and never contact each other.
- Evidence before claims: "passes" and "fixed" carry the command and its output.
"""


def host_appendix(persona, team, host) -> str:
    """§4.7 — how to address the team on this host, generated from hosts/<tool>.yaml."""
    d = host["delegation"]
    if persona["role"] != "primary":
        extra = ""
        if host["host"] == "antigravity":
            # measured: an explicit tools list omitting invoke_subagent really does bite (E19)
            extra = (" Your `tools` list omits `invoke_subagent`, so the tool is genuinely "
                     "absent rather than merely forbidden.")
        return ("## Addressing the team\n\n"
                "You have no spawn tool on this host." + extra +
                " If the work needs another persona, say so under follow-ups and let the "
                "Tech-Lead delegate.")

    names = persona["capabilities"]["delegate"]
    addressed = ", ".join(d["address_form"].format(name=n) for n in names)
    lines = ["## Addressing the team", ""]
    if host["host"] == "codex":
        lines.append(
            f"To delegate, {d['spawn_verb']} with `agent_type` exactly one of: {addressed}. "
            f"The runtime refuses an unknown type with "
            f"`{d['unknown_type_error'].format(name='<name>')}` — a loud failure, so if you "
            f"see it the personas are not installed or the project is not trusted; say so "
            f"rather than working around it.")
        lines.append("")
        lines.append(d["concurrency_note"] + ", so delegate in waves; a spawn past the limit "
                     "is refused, not queued.")
    elif host["host"] == "claude":
        lines.append(
            f"To delegate, use the `{d['tool']}` tool with `{d['parameter']}` exactly one of: "
            f"{addressed}.")
        lines.append("")
        lines.append("The qualified `e-colleagues:` prefix is required — a bare name does not "
                     "resolve. Never delegate to a built-in type ("
                     + ", ".join(d["builtins_to_deny"]) + ").")
    elif host["host"] == "opencode":
        lines.append(
            f"To delegate, use the `{d['tool']}` tool with `{d['parameter']}` exactly one of: "
            f"{addressed}. The allowlist is enforced by the runtime, so an attempt to reach "
            f"anyone else is refused rather than silently permitted.")
    elif host["host"] == "antigravity":
        lines.append(
            f"To delegate, use `{d['tool']}` with one of: {addressed}.")
    return "\n".join(lines)


def render_body(persona, team, host) -> str:
    """Compose one persona body from the §4 skeleton, in order."""
    primary = persona["role"] == "primary"
    parts = [
        f"# {persona['display']}",
        "",
        persona["_body"],
        "",
        f"Prefix every message you send with your signature: `{persona['signature'].strip()}`",
        "",
        shared("tree-primary" if primary else "tree"),
        shared("rules").replace("{{r4}}", " ".join(persona["_front"]["r4"].split())),
    ]
    if primary:
        parts.append(shared("lead-rules"))
    parts.append(
        shared("lens")
        .replace("{{lens_name}}", persona["lens"]["name"])
        .replace("{{paths_hint}}", ", ".join(f"`{p}`" for p in persona["lens"]["paths_hint"]))
    )
    if not primary:
        parts.append(shared("return"))
    if primary:
        parts.append(shared("lead-conduct"))
    if host.get("instructions", {}).get("body_carries_contract"):
        parts.append(CONTRACT.strip())
    parts.append(host_appendix(persona, team, host))
    return "\n\n".join(p for p in parts if p).strip() + "\n"


def toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')


def render_codex(personas, team, host, roster):
    """Specialists become role TOMLs; the tech-lead becomes developer_instructions [CX-06]."""
    written = {}
    caps = host["capabilities"]
    for name in roster:
        p = personas[name]
        body = render_body(p, team, host)
        if p["role"] == "primary":
            continue
        mode = caps["edit_true"] if p["capabilities"]["edit"] else caps["edit_false"]
        desc = " ".join(p["description"].split())
        lines = [
            f'name = "{p["name"]}"',
            f'description = "{toml_escape(desc)}"',
            f'sandbox_mode = "{mode["sandbox_mode"]}"',
            f'approval_policy = "{mode["approval_policy"]}"',
            'developer_instructions = """',
            toml_escape(body).rstrip(),
            '"""',
        ]
        written[host["agent_file"]["path"].format(name=name)] = "\n".join(lines) + "\n"

    lead = personas["tech-lead"]
    lead_body = toml_escape(render_body(lead, team, host)).rstrip()
    written["dist/codex/e-colleagues.config.toml"] = (
        "# codex --profile e-colleagues  (E14)\n"
        "# Generated by tools/gen.py — do not edit.\n"
        'developer_instructions = """\n' + lead_body + '\n"""\n'
    )
    written["dist/codex/config.snippet.toml"] = (
        "# Managed region for a project .codex/config.toml (E22). Generated — do not edit.\n"
        "# e-colleagues:begin\n"
        'developer_instructions = """\n' + lead_body + '\n"""\n'
        "project_doc_max_bytes = 65536\n"
        "# e-colleagues:end\n"
    )
    return written


def render_floor(personas, team, host, roster):
    """The portable floor: the tech-lead as a skill (D7). No host-only tokens [CX-12][AG-10]."""
    lead = personas["tech-lead"]
    body = render_body(lead, team, host)
    desc = " ".join(lead["description"].split())
    return {
        "skills/ec-tech-lead/SKILL.md": (
            "---\n"
            "name: ec-tech-lead\n"
            f"description: Adopt the Tech-Lead operating contract for this thread. {desc}\n"
            "---\n\n"
            f"{BANNER}\n\n"
            "Adopt the following contract for the rest of this thread.\n\n"
            + body
        )
    }


def render_team_json(personas, team):
    """Data for scripts that ship to users.

    `bootstrap.py` is standard-library only (§6), so it cannot read YAML. This carries the
    whole catalog and every profile, not one baked roster: the package ships one artifact and
    the project chooses its profile at init time (D3).
    """
    return {
        "version": team["version"],
        "catalog": list(team["catalog"]),
        "profiles": {k: list(v) for k, v in team["profiles"].items()},
        "personas": {
            n: {
                "display": personas[n]["display"],
                "signature": personas[n]["signature"],
                "role": personas[n]["role"],
                "spawn_name": n if personas[n]["role"] != "primary" else None,
                "lens": personas[n]["lens"]["name"],
            }
            for n in team["catalog"]
        },
    }



def yaml_scalar(v: str) -> str:
    """Quote a frontmatter value when it could be misread.

    A routing sentence always contains a colon, and an unquoted colon is a YAML error that
    `claude plugin validate` silently repairs rather than reports (experiments.md E15), so
    the generator must never emit one.
    """
    if any(c in v for c in ':#{}[]&*!|>%@`"\'') or v.strip() != v:
        return '"' + v.replace('\\', '\\\\').replace('"', '\\"') + '"'
    return v


def render_claude(personas, team, host, roster):
    """Claude dialect: a tools allowlist for read-only personas, nothing for the primary."""
    out = {}
    caps = host["capabilities"]
    for name in roster:
        p = personas[name]
        fm = [f"name: {p['name']}",
              f"description: {yaml_scalar(' '.join(p['description'].split()))}",
              f"model: {p['model']}"]
        if p["role"] == "primary":
            pass                      # no tools key at all [CC-09]
        elif p["capabilities"]["edit"]:
            fm.append("disallowedTools: " + ", ".join(caps["edit_true"]["disallowed_tools"]))
        else:
            fm.append("tools: " + ", ".join(caps["edit_false"]["tools"]))
        body = render_body(p, team, host)
        out[host["agent_file"]["path"].format(name=name)] = (
            "---\n" + "\n".join(fm) + "\n---\n\n" + body)
    return out


def render_opencode(personas, team, host, roster):
    """opencode dialect: opencode's own permission vocabulary, never Claude's tool names."""
    out = {}
    caps = host["capabilities"]
    for name in roster:
        p = personas[name]
        perm: dict = {}
        perm.update(caps["edit_true"] if p["capabilities"]["edit"] else caps["edit_false"])
        if not p["capabilities"]["web"]:
            perm.update(caps["no_web"])
        if p["capabilities"]["delegate"]:
            perm["task"] = {"*": "deny", **{n: "allow" for n in p["capabilities"]["delegate"]}}
        lines = [f"description: {yaml_scalar(' '.join(p['description'].split()))}",
                 f"mode: {'primary' if p['role'] == 'primary' else 'subagent'}",
                 "permission:"]
        for k, v in perm.items():
            if isinstance(v, dict):
                lines.append(f"  {k}:")
                for pat, act in v.items():
                    lines.append(f'    "{pat}": {act}')
            else:
                lines.append(f"  {k}: {v}")
        out[host["agent_file"]["path"].format(name=name)] = (
            "---\n" + "\n".join(lines) + "\n---\n\n" + render_body(p, team, host))

    cfg = {
        "$schema": host["config"]["schema"],
        "default_agent": "tech-lead",
        "permission": {"task": {"*": "deny",
                                **{n: "allow" for n in personas["tech-lead"]["capabilities"]["delegate"]
                                   if n in roster}}},
    }
    out[host["config"]["path"]] = json.dumps(cfg, indent=2) + "\n"
    # opencode writes these into any config directory on first run [OC-10]
    out["dist/opencode/.gitignore"] = "node_modules/\npackage.json\npackage-lock.json\n"
    return out


def render_antigravity(personas, team, host, roster):
    """Antigravity dialect: ONLY names in the measured registry (E17)."""
    out = {}
    caps = host["capabilities"]
    registry = set(host["tool_registry"])
    for name in roster:
        p = personas[name]
        tools = list(caps["read"]) + list(caps["search"])
        if p["capabilities"]["shell"]:
            tools += caps["shell"]
        if p["capabilities"]["web"]:
            tools += caps["web"]
        if p["capabilities"]["edit"]:
            tools += caps["edit"]
        if p["capabilities"]["delegate"]:
            tools += caps["delegate"]
        bad = [t for t in tools if t not in registry]
        if bad:                       # a name outside the registry aborts the agent (E17)
            raise SystemExit(f"gen.py: {name} would emit tool names outside the measured "
                             f"registry: {bad}")
        primary = p["role"] == "primary"
        fm = [f"name: {p['name']}",
              f"description: {yaml_scalar(' '.join(p['description'].split()))}",
              f"mainAgent: {'true' if primary else 'false'}",
              f"subagent: {'false' if primary else 'true'}",
              f"model: {p['model']}",
              "tools:"] + [f"  - {t}" for t in tools]
        out[host["agent_file"]["path"].format(name=name)] = (
            "---\n" + "\n".join(fm) + "\n---\n\n" + render_body(p, team, host))
    return out


def build(roster_name="default"):
    team, personas = load_team(), load_personas()
    hosts = {h: yaml.safe_load((HOSTS / f"{h}.yaml").read_text())
             for h in ("codex", "claude", "opencode", "antigravity")}
    roster = team["profiles"][roster_name]
    files = {}
    files.update(render_codex(personas, team, hosts["codex"], roster))
    files.update(render_claude(personas, team, hosts["claude"], roster))
    files.update(render_opencode(personas, team, hosts["opencode"], roster))
    files.update(render_antigravity(personas, team, hosts["antigravity"], roster))
    files.update(render_floor(personas, team, hosts["codex"], roster))
    files["dist/team.json"] = json.dumps(
        render_team_json(personas, team), indent=2, ensure_ascii=False) + "\n"
    return files


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the tree is stale")
    ap.add_argument("--profile", default="default")
    a = ap.parse_args()
    files = build(a.profile)
    stale = []
    for rel, content in sorted(files.items()):
        path = ROOT / rel
        if a.check:
            if not path.exists() or path.read_text() != content:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if a.check:
        if stale:
            print("stale (run tools/gen.py):")
            for s in stale:
                print("  " + s)
            return 1
        print(f"generated tree is current ({len(files)} files)")
        return 0
    print(f"wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
