#!/usr/bin/env python3
"""Render every host dialect from personas/ + team.yaml + hosts/.

Generated trees are never hand-edited; `check.py --drift` fails if they differ from what
this script would write. Requires PyYAML (a dev-time dependency); scripts that ship to
users, such as the bootstrap script, stay standard-library only.
"""
from __future__ import annotations

import argparse
import pathlib
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("gen.py needs PyYAML: pip install pyyaml")

ROOT = pathlib.Path(__file__).resolve().parent.parent
PERSONAS = ROOT / "personas"
SHARED = PERSONAS / "_shared"
HOSTS = ROOT / "hosts"
DIST = ROOT / "dist"

BANNER = "<!-- generated by tools/gen.py from personas/ — do not edit -->"


def load_team():
    return yaml.safe_load((ROOT / "team.yaml").read_text())


def load_personas():
    out = {}
    for f in sorted(PERSONAS.glob("*.yaml")):
        d = yaml.safe_load(f.read_text())
        body = (PERSONAS / d["prompt"]).read_text()
        # the prompt file carries its own tiny frontmatter, currently just r4
        _, fm, rest = body.split("---", 2)
        d["_front"] = yaml.safe_load(fm) or {}
        d["_body"] = rest.strip()
        out[d["name"]] = d
    return out


def shared(name: str) -> str:
    return (SHARED / f"{name}.md").read_text().strip()


def host_appendix(persona, team, host) -> str:
    """§4.7 — how to address the team on this host."""
    if persona["role"] != "primary":
        return (
            "## Addressing the team\n\n"
            "You have no spawn tool on this host. If the work needs another persona, say so "
            "under follow-ups and let the Tech-Lead delegate."
        )
    names = ", ".join(persona["capabilities"]["delegate"])
    d = host["delegation"]
    return (
        "## Addressing the team\n\n"
        f"To delegate on this host, {d['spawn_verb']} with `agent_type` exactly one of: "
        f"{names}. The runtime refuses an unknown type with "
        f"`{d['unknown_type_error'].format(name='<name>')}`, which is a loud failure rather "
        "than a silent one — if you see it, the personas are not installed or the project is "
        "not trusted, and you should say so rather than working around it.\n\n"
        f"{d['concurrency_note']}, so delegate in waves rather than firing every persona at "
        "once; a spawn past the limit is refused, not queued."
    )


def render_body(persona, team, host) -> str:
    """Compose one persona body from the §4 skeleton, in order."""
    primary = persona["role"] == "primary"
    parts = [
        f"# {persona['display']}",
        "",
        persona["_body"],
        "",
        f"Prefix every message you send with your signature: `{persona['signature'].strip()}`",
        "",
        shared("tree-primary" if primary else "tree"),
        shared("rules").replace("{{r4}}", " ".join(persona["_front"]["r4"].split())),
    ]
    if primary:
        parts.append(shared("lead-rules"))
    parts.append(
        shared("lens")
        .replace("{{lens_name}}", persona["lens"]["name"])
        .replace("{{paths_hint}}", ", ".join(f"`{p}`" for p in persona["lens"]["paths_hint"]))
    )
    if not primary:
        parts.append(shared("return"))
    if primary:
        parts.append(shared("lead-conduct"))
    parts.append(host_appendix(persona, team, host))
    return "\n\n".join(p for p in parts if p).strip() + "\n"


def toml_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')


def render_codex(personas, team, host, roster):
    """Specialists become role TOMLs; the tech-lead becomes developer_instructions [CX-06]."""
    written = {}
    caps = host["capabilities"]
    for name in roster:
        p = personas[name]
        body = render_body(p, team, host)
        if p["role"] == "primary":
            continue
        mode = caps["edit_true"] if p["capabilities"]["edit"] else caps["edit_false"]
        desc = " ".join(p["description"].split())
        lines = [
            f'name = "{p["name"]}"',
            f'description = "{toml_escape(desc)}"',
            f'sandbox_mode = "{mode["sandbox_mode"]}"',
            f'approval_policy = "{mode["approval_policy"]}"',
            'developer_instructions = """',
            toml_escape(body).rstrip(),
            '"""',
        ]
        written[host["agent_file"]["path"].format(name=name)] = "\n".join(lines) + "\n"

    lead = personas["tech-lead"]
    lead_body = toml_escape(render_body(lead, team, host)).rstrip()
    written["dist/codex/e-colleagues.config.toml"] = (
        "# codex --profile e-colleagues  (E14)\n"
        "# Generated by tools/gen.py — do not edit.\n"
        'developer_instructions = """\n' + lead_body + '\n"""\n'
    )
    written["dist/codex/config.snippet.toml"] = (
        "# Managed region for a project .codex/config.toml (E22). Generated — do not edit.\n"
        "# e-colleagues:begin\n"
        'developer_instructions = """\n' + lead_body + '\n"""\n'
        "project_doc_max_bytes = 65536\n"
        "# e-colleagues:end\n"
    )
    return written


def render_floor(personas, team, host, roster):
    """The portable floor: the tech-lead as a skill (D7). No host-only tokens [CX-12][AG-10]."""
    lead = personas["tech-lead"]
    body = render_body(lead, team, host)
    desc = " ".join(lead["description"].split())
    return {
        "skills/ec-tech-lead/SKILL.md": (
            "---\n"
            "name: ec-tech-lead\n"
            f"description: Adopt the Tech-Lead operating contract for this thread. {desc}\n"
            "---\n\n"
            f"{BANNER}\n\n"
            "Adopt the following contract for the rest of this thread.\n\n"
            + body
        )
    }


def build(roster_name="default"):
    team, personas = load_team(), load_personas()
    host = yaml.safe_load((HOSTS / "codex.yaml").read_text())
    roster = team["profiles"][roster_name]
    files = {}
    files.update(render_codex(personas, team, host, roster))
    files.update(render_floor(personas, team, host, roster))
    return files


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if the tree is stale")
    ap.add_argument("--profile", default="default")
    a = ap.parse_args()
    files = build(a.profile)
    stale = []
    for rel, content in sorted(files.items()):
        path = ROOT / rel
        if a.check:
            if not path.exists() or path.read_text() != content:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if a.check:
        if stale:
            print("stale (run tools/gen.py):")
            for s in stale:
                print("  " + s)
            return 1
        print(f"generated tree is current ({len(files)} files)")
        return 0
    print(f"wrote {len(files)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
